[package]
name = "sosa"
version = "5.0.0"
edition = "2021"
repository = "https://github.com/fraterenz/sosa"
description = "Stochastic simulation algorithm (SSA) with a Monte-Carlo generating method"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0"
log = "0.4.29"
rand_core = "0.10"
thiserror = "2"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.10"
